# This workflow will do a clean install of node dependencies and run the checker.

name: LibCal check

on:
  schedule:
    # Run every day at 4:05 AM.
    - cron: '5 4 * * *'

  workflow_dispatch:

defaults:
  run:
    working-directory: tools/check-consultation-calendars

jobs:
  check:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run build --if-present
    - run: node index.js